### ISSUE TITLE
importing other models from a model

### ISSUE THREAD

**Issue by echonax** [damienpontifex/TypescriptAngular2CodeGen#1]
First of all, thank you for this project. I've recently stumbled upon a problem; 
-import * from "api.d"; doesn't work anymore in new versions of tsc I believe. Instead
 import * as lib from  './api.d'; is used.

-When you try to import a model from another model ( like a models field is in type of another model) the model can't find the name of the other model.

**Comment by damienpontifex** [comment]
- On the first point, you are correct, I stumbled across the same issue. The change inside the code further on would need to add the lib prefix to the models. i.e. `lib.Model`

- I hadn't solved this as when importing the models, I was also getting the generator trying to import native types like string, bool etc. I hadn't been able to figure out why it was also importing these rather than just the custom types. Maybe another definition inside the Java code is needed to ignore native types from being exported for the models.

_As a note, I haven't been working on this due to priorities in other work, but left this here so people could develop on it. I hope you can make progress and look forward to see the work._

**Comment by echonax** [comment]
Thanks for the answer,

codegen has an option, language-specific-primitives, which might solve the issue. 
ex: java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i api_v.0.1.0.json -o ./src -l typescript-angular -t ./typescriptangular2codegen --language-specific-primitives String,boolean,Boolean,number,Number,string,Date,Array,any
I will check it out tho.

**Comment by damienpontifex** [comment]
Some resolutions with #2 but still have some issues being generated types are:

`lib.string` should be `string`
`Observable<lib.{}>` should be `Observable<{}>`
`Observable<lib.Array<Pet>>` should be `Observable<Array<lib.Pet>>`

**Comment by damienpontifex** [comment]
Closed as others have merged this work into the main swagger-codegen repo now
